### PR TITLE
Fix 0.12.0 recipe/meta.yaml

### PR DESCRIPTION
**Pull request by DunklesArchipel**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by saraedum** [comment]
This does not seem to work. Can we maybe do this with the next release of svgdigitizer?

**Comment by DunklesArchipel** [comment]
> This does not seem to work. Can we maybe do this with the next release of svgdigitizer?

This is indeed intriguing. I do not understand why these tests are failing.
All tests within svgdigitizer which does not contain `scipy` and `svg.path` (neither in the setup nor the environment file) succeed.
I looked into the packages and both packages are part of  `svgpathtools`, so they should in principle be installed along with that module.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@DunklesArchipel can you check that box on the right? "Allow edits from maintainers"

**Comment by saraedum** [comment]
scipy is an optional dependency of svgpathtools. If it is not installed, some features do not work.

**Comment by saraedum** [comment]
(It should probably not be removed from upstream as a dependency either.)

**Comment by DunklesArchipel** [comment]
> @DunklesArchipel can you check that box on the right? "Allow edits from maintainers"

Does not appear for me here on conda-forge. :(

**Comment by DunklesArchipel** [comment]
> (It should probably not be removed from upstream as a dependency either.)

So I probably simply bump to a new version of svgdigitizer, placing a note in the setup and environment files?

**Comment by saraedum** [comment]
You don't have this setting? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by DunklesArchipel** [comment]
Nope. I do see it in our repositories.

**Comment by saraedum** [comment]
That's odd. Maybe you need to set it when creating the PR.

**Pull request closed without merging**
